### PR TITLE
Zodiac

### PR DESCRIPTION
**Pull request by Konohamaruu**

### CODE REVIEW

**Comment by MartinKuschnik** [comment]
Is this the update for patch 3.22?

MEMMAP does not work with hex value.

**Comment by Konohamaruu** [comment]
Hi, its the update for 3.25.

Not too sure what i was doing, just wanted to update the addresses for the zodiac glass to work again :(

**Comment by MartinKuschnik** [comment]
MEMMAP should look like the following if 0x010917A8 is the new base address offset.

(0x010917A8 = 17373096)

```
<?xml version="1.0"?>
<FFXIVMemoryMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ItemSetPointer>
    <BaseAddressOffset>17373096</BaseAddressOffset>
    <Offsets>
      <int>64</int>
      <int>0</int>
    </Offsets>
  </ItemSetPointer>
</FFXIVMemoryMap>
```

**Comment by Konohamaruu** [comment]
Thanks so much, and how would i update the memory address? Would it be possible if you could update it as i am totally clueless lol.

Thanks!

**Comment by MartinKuschnik** [comment]
The FFXIVMemoryMap.cs file contains the address which is used in the debug mode.
The release version pulls the address from the github repo via the MEMMAP file.

Could you please update the MEMMAP like i mentioned in the comment.

**Pull request closed without merging**
