### PR TITLE
Patch 3.2

### PR DESCRIPTION
**Pull request by MorbidA**

### CODE REVIEW

**Comment by MartinKuschnik** [comment]
Looks good.

**Comment by MartinKuschnik** [comment]
Please let me know whether the released version is working again.

**Comment by MorbidA** [comment]
Doesn't work, the offset is correct though can see the ID changing when swapping weapon in CE as per the memory address change instructions.

Pointer: ffxiv.exe+0108D728 offset1: 0x8 offset2: 0x40

**Comment by MartinKuschnik** [comment]
Maybe they changed the memory layout a bit.
In this case it harder to update the reading.

If you have the right weapon, you could set a breakpoint to the OverlayViewModelOnEquippedMainHandIDChanged method and have a look to the data.

**Comment by MorbidA** [comment]
Nevermind it works, but only for debug builds, release builds doesn't work for some reason.

**Comment by MartinKuschnik** [comment]
The debug mode forces the application to use the mem addresses form the FFXIVMemoryMap.Default property. The release version downloads the addresses by the MEMMAP file.

**Comment by MartinKuschnik** [comment]
I think you entered a wrong value into the MEMMAP file.
0x108D728 -> 17356584 (not 17356576)

**Comment by MorbidA** [comment]
Ah yes that would explain it :) and it does indeed work now.

**Comment by MartinKuschnik** [comment]
Thanks for the update.

**Pull request merged**
